---
# Use item/enchantmet/effect ids

# Kit
HelmetName: "§o§bSoupPvP Helmet"
Helmet: "306"
ChestplateName: "§o§bSoupPvP ChestPlate"
Chestplate: "307"
LeggingsName: "§o§bSoupPvP Leggings"
Leggings: "308"
BootsName: "§o§bSoupPvP Boots"
Boots: "309"
WeaponName: "§o§bSoupPvP Sword"
Weapon: "267"

# Enchantments
Enchantment1: "0"
Level1: "2"
Enchantment2: "17"
Level2: "9000"
AllowWeaponToGetEnchantTwo: "True" # True or False

# Effects
Effect1: "1"
Duration1: "99999"
Amplifier1: "0"
Effect2: "1"
Duration2: "99999"
Amplifier2: "0"

# Soup
SoupName: "§o§l§4PvPSoup"
SoupLore: "§o§5* Right/Left click to consume{line}§o§5* Gain 3 hearts"
HealthGained: "3" # The health added when the soup is clicked on

# Empty Soup Bowl
BowlName: "§oEmpty Bowl"
BowlLore: "§5* Worthless Empty Bowl"

# Kill health/soup
KillHealth: "True"
HealthGainedPerKill: "3"
KillSoup: "True"
SoupGainedPerKill: "5"

# Special Stew Effects
# DM me on discord for suggestions for this, it can give you effects or do anything when consumed. I will add kill streaks to so you can set it to when you get one of them. Discord: @Zyqia#9178

# Other Plugin Spcs
# {player} => The player
# {killer} => The Killer
# {victim} => The Victim
JoinMsg: "§b+ §8{player}"
QuitMsg: "§c- §8{player}"
KillMsg: "{killer} has killed {victim}"

NoFall: "True"
AntiVoid: "True"
NoHunger: "True"
KitOnJoin: "True"
KitOnRespawn: "True"
AllowDroppingItems: "True"
...